const express = require("express");
const app = express();
const port = process.env.PORT || 8080;
const router = require("./routes.js");
const fs = require("fs");
var pool = require("./databaseConnection");
//Reading Commands from database.sql file
const sqlCommands = fs.readFileSync("./database.sql").toString();
//Creating database tables: poll_answers, poll_questions
const createTables = async () => {
  try {
    await pool.query(sqlCommands);
    console.log("Database setup and connection successfull");
  } catch (err) {
    console.error("Table creation failed:", err);
  }
};

createTables();

app.use(express.static("./public")); //serves static files generated by Svelte application
app.use(express.json());

//Routes are moved to a separate for better structure of the application
//All routes have /api subpath in the url.
app.use("/api", router);

app.listen(port, () => {
  console.log(`Server running on port ${port}`);
});
